[book]
title = "いとエモき端末心得"
authors = ["k-kozika","asterf",]
language = "ja"

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/textbook/"
default-theme = "light"
git-repository-url = "https://github.com/techno-tutors/textbook/tree/main/"
edit-url-template = "https://github.com/techno-tutors/textbook/edit/main/{path}"
preferred-dark-theme = "ayu"

[output.epub]
optional = true
additional-css = ["./assets/main.css"]
curly-quotes = false
epub-version = 3
footnote-backrefs = true

[output.linkcheck]
optional = true

